CREATE DATABASE TROLEO
USE TROLEO

CREATE TABLE [USER]
(
CODU	INT PRIMARY KEY identity(1,1),
EMAIL	VARCHAR(100),
SENHA	VARCHAR(20) 
)


CREATE TABLE CLIENTE 
(
CODC	INT PRIMARY KEY,
NOME	VARCHAR(50),
VEICULO	VARCHAR(50),
PLACA	VARCHAR(20),
EMAIL	VARCHAR(100)
)

CREATE TABLE OLEO
(
CODO		INT PRIMARY KEY,
NOME		VARCHAR(100),
CATEGORIA	VARCHAR(50),
TPOLEO		VARCHAR(50),
FABRICANTE	VARCHAR(50),
VALOR		DECIMAL(8,2) 
)

CREATE TABLE STROLEO
(
CODS	INT PRIMARY KEY identity(1,1),
DATAS	DATETIME DEFAULT GETDATE(),
CLIENTE VARCHAR(50),
OLEO	VARCHAR(50),
CATEGORIA VARCHAR(50),
TIPO	VARCHAR(50),
FABRICANTE	VARCHAR(50),
VALOR		DECIMAL(8,2),
qtde		int,
EMAILC		VARCHAR(50)
)


bulk insert [USER]
from 'C:\Users\Particular\Documents\GitHub\TROLEO\usuarios.txt'
with (codepage='ACP', fieldterminator = ';')


bulk insert CLIENTE
from 'C:\Users\Particular\Documents\GitHub\TROLEO\Clientes.txt'
with (codepage='ACP', fieldterminator = ';')

bulk insert OLEO
from 'C:\Users\Particular\Documents\GitHub\TROLEO\Oleos.txt'
with (codepage='ACP', fieldterminator = ';')

SELECT*FROM [USER]

SELECT NOME FROM CLIENTE


SELECT * FROM OLEO